// Batch EXPORT-PROMPT generator for the segment backfill. As of 2026-09-21 this
// script no longer calls any AI/search provider directly (see CLAUDE.md's "no
// automated API calls anywhere in the app" entry) — it finds every Model with
// segment == null (a small legacy backlog — records written before the schema made
// segment required, or by an older import path that didn't yet enforce the "never
// null" rule — see models/Model.ts / lib/modelDiscovery.ts) and writes one
// classification prompt per model to a single batch file under raw-data/.
//
// This script NEVER writes to MongoDB and never calls lib/aiProvider.ts. Paste each
// prompt into an external AI chat (Kimi/Gemini/DeepSeek), which will reply with a
// single segment string, then apply it yourself — there's no dedicated import panel
// for this one field, so use the model's own edit UI, or
// `PUT /api/models/<id>` with body `{ "segment": "<answer>", "segment_confidence":
// "inferred" }` (this script never claims "confirmed", since it's a single
// non-grounded classification, not the full researchModel()/discoverModels()
// grounded pipeline — a source-backed "confirmed" segment should instead come from
// the normal per-brand "Discover models" flow or the manual Kimi/DeepSeek
// round-trip, both of which DO search).
//
// Usage:
//   npm run backfill-segment                (full run)
//   npm run backfill-segment -- --limit 3   (only the first 3 models)

import dotenv from "dotenv";
dotenv.config({ path: [".env.local", ".env"], quiet: true });
import fs from "fs";
import path from "path";
import mongoose from "mongoose";
import "../models/Brand";
import ModelSchema, { SEGMENTS } from "../models/Model";
import type { IBrand } from "../types";

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  throw new Error("Missing MONGODB_URI. Copy .env.example to .env and set it.");
}

interface CliOptions {
  limit?: number;
}

function parseArgs(): CliOptions {
  const args = process.argv.slice(2);
  const options: CliOptions = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--limit") options.limit = Number(args[++i]);
  }
  return options;
}

function buildPrompt(brandName: string, modelName: string, generation: string | undefined, bodyType: string | undefined): string {
  return `You are classifying a Chinese-market vehicle's market segment for a database. No web search is available for this task — use your own knowledge of the vehicle's body type, size, and market positioning. Respond in English only.

Vehicle: "${brandName} ${modelName}"${generation ? ` (${generation})` : ""}${bodyType ? `\nKnown body type: ${bodyType}` : ""}

Classify its segment as EXACTLY one of: ${SEGMENTS.join(", ")}.

Respond with ONLY that single segment string, nothing else — no punctuation, no explanation, no markdown.`;
}

async function run() {
  const { limit } = parseArgs();
  await mongoose.connect(MONGODB_URI!);

  const targets = (await ModelSchema.find({
    $or: [{ segment: null }, { segment: { $exists: false } }],
  })
    .populate<{ brand_id: IBrand }>("brand_id")
    .lean()) as unknown as (Record<string, unknown> & { brand_id: IBrand })[];

  const scoped = limit ? targets.slice(0, limit) : targets;
  console.log(`Found ${targets.length} Model doc(s) with a null/missing segment.${limit ? ` Writing prompts for first ${scoped.length} (--limit).` : ""}`);

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const outPath = path.resolve(`raw-data/segment-backfill-batch-prompts-${timestamp}.md`);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  const sections: string[] = [];
  for (let i = 0; i < scoped.length; i++) {
    const m = scoped[i];
    const brandName = m.brand_id?.name_en ?? m.brand_id?.name ?? "Unknown brand";
    const modelName = m.name as string;
    const prompt = buildPrompt(brandName, modelName, m.generation as string | undefined, m.body_type as string | undefined);

    console.log(`[${i + 1}/${scoped.length}] ${brandName} ${modelName}: prompt built`);
    sections.push(
      `## ${brandName} ${modelName}\n\n- Model DB id: \`${String(m._id)}\`\n- Apply the answer via this model's edit UI, or \`PUT /api/models/${String(
        m._id
      )}\` with body \`{ "segment": "<answer>", "segment_confidence": "inferred" }\`.\n\n\`\`\`\n${prompt}\n\`\`\`\n`
    );
  }

  fs.writeFileSync(
    outPath,
    `# Segment backfill export prompts — ${timestamp}\n\n${scoped.length} model(s) have a null/missing segment. Generated by scripts/backfill-segment.ts. No AI provider was called — paste each prompt below into an external AI chat, then apply the single-word answer yourself (segment_confidence: "inferred").\n\n${sections.join(
      "\n---\n\n"
    )}`
  );

  console.log(`\nWrote ${scoped.length} prompt(s) to ${outPath}`);
  console.log(`This file was NOT written to MongoDB and no AI provider was called.`);

  await mongoose.disconnect();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
