// Batch EXPORT-PROMPT generator for brand_workshop_overrides — targets only brands
// with a confirmed Morocco market presence (Model.morocco_price_confirmed === true),
// not global sales volume, per the explicit review decision on this feature. Does NOT
// run against all brands: this was deliberately narrow even when it called an AI
// provider directly, and most brands have zero public brand-specific workshop
// documents.
//
// Three distinct search queries per brand (lib/workshopOverrideResearch.ts's
// buildOverrideSearchQueries) are folded into the single kickoff prompt below.
//
// As of 2026-09-21 this script no longer calls any AI/search provider directly (see
// CLAUDE.md's "automated research calls removed" entries) — it writes one
// kickoff+format prompt pair per qualifying brand to a single batch file under
// raw-data/. This feature has no UI button anywhere in the app, so paste each prompt
// into an external AI chat by hand, then paste the resulting JSON straight into
// `npm run apply-workshop-overrides-batch` (which still validates via
// validateResearchedOverride/passesSpecificityGate before any DB write).
//
// The dead-brand tracking (raw-data/workshop-override-dead-brands.json) that used to
// skip brands whose automated research came back thin/not_found no longer applies —
// there is no automated result to judge "dead" from now, so every qualifying brand
// gets a prompt on every run. If this file already exists from before the change, it
// is left untouched (informational only) but no longer read or written here.
//
// NEVER writes to MongoDB.
//
// Usage:
//   npm run research-workshop-overrides                  (all confirmed-Morocco brands)
//   npm run research-workshop-overrides -- --limit 3      (first 3, for a quick test)

import dotenv from "dotenv";
dotenv.config({ path: [".env.local", ".env"], quiet: true });
import fs from "fs";
import path from "path";
import mongoose from "mongoose";
import Brand from "../models/Brand";
import ModelSchema from "../models/Model";
import { buildOverrideFormatPrompt, buildOverrideKickoffPrompt } from "../lib/workshopOverrideResearch";

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  throw new Error("Missing MONGODB_URI. Copy .env.example to .env and set it.");
}

const args = process.argv.slice(2);
const limitArg = args.find((a) => a.startsWith("--limit"));
const limit = limitArg ? parseInt(limitArg.split("=")[1] ?? args[args.indexOf(limitArg) + 1], 10) : undefined;

async function main() {
  await mongoose.connect(MONGODB_URI as string);

  // Same signal CLAUDE.md's listing convention treats as "confirmed Morocco
  // market presence" — Model.morocco_price_confirmed — aggregated up to brand
  // level.
  const rankedBrandIds = await ModelSchema.aggregate([
    { $match: { morocco_price_confirmed: true, morocco_price_dh: { $ne: null } } },
    { $group: { _id: "$brand_id", confirmedCount: { $sum: 1 } } },
    { $sort: { confirmedCount: -1 } },
  ]);

  const brands = await Brand.find({ _id: { $in: rankedBrandIds.map((r) => r._id) } }).lean();
  const brandById = new Map(brands.map((b) => [String(b._id), b]));
  let targets = rankedBrandIds
    .map((r) => ({ brand: brandById.get(String(r._id)), confirmedCount: r.confirmedCount }))
    .filter((t): t is { brand: NonNullable<typeof t.brand>; confirmedCount: number } => Boolean(t.brand));

  console.log(`${targets.length} brand(s) with a confirmed Morocco-priced model (the full ranked list):`);
  for (const t of targets) console.log(`  - ${t.brand.name} (${t.confirmedCount} confirmed model(s))`);

  if (limit) targets = targets.slice(0, limit);

  const sections = targets.map(({ brand }) => {
    const input = { brandName: brand.name_en ?? brand.name, brandNameCn: brand.name_cn };
    const prompt = `${buildOverrideKickoffPrompt(input)}\n\n---\n\n${buildOverrideFormatPrompt()}`;
    return `## ${brand.name}\n\n- Brand DB id: \`${String(brand._id)}\`\n- Paste the resulting JSON into \`npm run apply-workshop-overrides-batch\`.\n\n\`\`\`\n${prompt}\n\`\`\`\n`;
  });

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const outPath = path.resolve(`raw-data/workshop-overrides-prompts-${timestamp}.md`);
  fs.writeFileSync(
    outPath,
    `# Workshop-override export prompts — ${timestamp}\n\nGenerated by scripts/research-brand-workshop-overrides.ts. No AI/search provider was called — paste each prompt below into an external AI chat, then run \`npm run apply-workshop-overrides-batch\` with the resulting JSON.\n\n${sections.join(
      "\n---\n\n"
    )}`
  );

  console.log(`\nWrote ${targets.length} export prompt(s) to ${outPath}.`);

  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
